# Generated by Django 4.2.6 on 2024-03-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null='False', upload_to='profile')),
                ('discipline', models.CharField(max_length=100)),
                ('actions', models.TextField()),
                ('achievement', models.CharField(max_length=100)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms.student')),
            ],
        ),
    ]
